name: deepgram_speech_to_text
description: >
  A simple Deepgram client for Dart and Flutter. 
  Made to simply transcribe audio from : File, URL, Stream or Raw data.
version: 1.0.2
repository: https://github.com/tempo-riz/deepgram_speech_to_text

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.2.0
  universal_io: ^2.2.2
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  dotenv: ^4.2.0
