name: deepgram_speech_to_text
description: >
  A Deepgram client for Dart and Flutter.
version: 2.0.0
repository: https://github.com/tempo-riz/deepgram_speech_to_text

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.2.1
  universal_file: ^1.0.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  dotenv: ^4.2.0
  will_it_run: ^1.0.4
