name: dart_example
description: A sample command-line application.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  deepgram_speech_to_text:
    path: ../../
  dotenv: ^4.2.0
  wav: ^1.3.0
  wav_io: ^2.0.3
  web_socket_channel: ^3.0.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
